name: Creates and Updates PR
on:
  push:
    branches:
    - test
  pull_request:
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: create-description
      run: "some script for creating PR description from the branch diff"
      id: description
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: ${GITHUB_REF}

