name: Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: echo Hello, world
  
  
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello
        includes-script: script.py
  
  DeployProd:
    name: Deploy to Production 
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo I am deploying!
